### ISSUE TITLE
As a user I would like to click on a shelve on a map

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#23]
# Description
The user should be able to long press on a shelve see what products are here.

The easy way: Check coordinates for the whole shelve ( You should step out a bit to get products that lie right outside the poly )
The hard way: Check in the area of the click

# Tasks
- [ ] Implement a long click on a polygon
- [ ] Get coordinates
- [ ] Create a new service or re-use search service.
- [ ] Get product list from service
- [ ] Present the result ins
- [ ] Documentation

# Test efforts
- [ ] Test that the correct coordinates are gathered and send with the service
- [ ] Do a full test when backend is finished.
