### ISSUE TITLE
Add map gestures

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#26]
# Description
The map should respond to touch and standard computer inputs, such as:
* Touch pan
* Pinch zoom
* Scroll zoom
* Mouse pan

# Tasks
- [ ] Add zoom buttons
- [ ] Add touch gestures
- [ ] Add scroll zoom
- [ ] Add doubleclick zoom
- [ ] Documentation

# Test efforts
- [ ] Tests on the map render should be updated
- [ ] Do manual tests to ensure that all the gestures work properly
- [ ] Test the performance of normal use.
