### ISSUE TITLE
Expand Map Selector and 2dmap to include current location

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#3]
# Description
Map selector should always get current booth location from #47         

It should display an error if no location is set:
A text above the screen saying "Booth not configured" with an option to acknowledge, and an option to go to settings. The acknowledgement should be saved for the session.

Map selector should pass the booth location on to the 2d map, letting it draw a red dot for the current booth.

# Tasks
* [x]  Map Selector
  * [x]  Get location from service
  * [x]  Implement error logic with component #51         
  * [x]  Pass booth location to 2D map
* [x]  2D Map
  * [x]  Render the booth location if avaliable
- [x] Documentation
  * [x]  Update the documentation for the Map Selector
  * [x]  Update the documentation for the 2D map component
  * [x]  Make a sequence diagram over the location flow and warning flow

# Test efforts
* [x]  Test error logic
* [x]  Test current location dot is rendered correctly
