### ISSUE TITLE
Fucntion for 2d map to figure ot map size

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#4]
# Description
A static class that should take outerpolygon and return biggest x and y coord and save it to state.

The state should be used by grid definition and viewbox.

# Tasks
- [x] Implement function
- [x] Set as the state
- [x] Use the state in viewbox and grid def
- [x] Update documentation

# Test efforts
- [x] A single test should be fine. Input an outer poly with a bunch of coordinates.
