### ISSUE TITLE
Make the map pretty

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#5]
# Description
The map is not quite pretty yet.

Create mockups, depending on layout talk

# Tasks
- [x] Mock ups
- [x] CSS
- [x] 2Dmap should preserve aspect ratio
- [ ] Map should fill as much of the screen as possible
- [ ] Result should be centered, so both start and finish is visible on the screen
- [ ] Documentation

# Test efforts
See that it is pretty

**Comment by sixfourtwo** [comment]
This is partly being handled in #14

**Comment by sixfourtwo** [comment]
Closed, since missing features will be done in this sprint
