### ISSUE TITLE
Long product descriptions should be shortened with an eclipse

### ISSUE THREAD

**Issue by sixfourtwo** [2019f46/leway#7]
# Description
Super long descriptions should be shortened. The product result should have a max height, and if the description would cause the box to exceed this height, it should be eclipsed.

All result boxes should have the same height.

# Tasks
- [x] Find a suitable max height
- [x] Max height should only be applied in the list, not when clicked
- [x] Implement eclipse on text
- [x] Documentation

# Test efforts
- [x] Test with a short description - Should be a short box
- [x] Test with a long description - Text should be shortened so the box stays short.

**Comment by sixfourtwo** [comment]
Almost completed in #14 
Missing tests for portrait mode.
